[package]
name = "lxc_run"
version = "0.1.0"
authors = [
    "Christian Brauner <christian.brauner@ubuntu.com>",
    "Wolfgang Bumiller <w.bumiller@proxmox.com>",
]

[dependencies]
libc = "0.2"

[build-dependencies]
bindgen = ">0.42.2"
