[package]
edition = "2018"
name = "lxc-sys"
version = "0.1.0"
authors = [
    "Christian Brauner <christian.brauner@ubuntu.com>",
    "Wolfgang Bumiller <w.bumiller@proxmox.com>",
]

[build-dependencies]
bindgen = ">0.42.2"
